---
swagger: "2.0"
info:
  version: "2019-09-10T05:47:29Z"
  title: "iot"
host: "cddgsfju77.execute-api.us-east-2.amazonaws.com"
basePath: "/dev1"
schemes:
- "https"
paths:
  /device:
    get:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "device_id"
        in: "query"
        required: true
        type: "string"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
    options:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
definitions:
  Empty:
    type: "object"
    title: "Empty Schema"
